version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0  # Use the appropriate .NET SDK version

    working_directory: ~/repo

    steps:
      - checkout

      # Restore dependencies
      - run:
          name: Restore dependencies
          command: dotnet restore

      # Build the project
      - run:
          name: Build
          command: dotnet build --configuration Release

      # Run tests
      - run:
          name: Test
          command: dotnet test --no-restore --verbosity normal

  deploy:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0  # Use the appropriate .NET SDK version

    working_directory: ~/repo

    steps:
      - checkout

      # Restore dependencies
      - run:
          name: Restore dependencies
          command: dotnet restore

      # Build the project
      - run:
          name: Build
          command: dotnet build --configuration Release

      # Deploy steps go here (e.g., publish, deploy to Azure, AWS, etc.)
